# SPDX-FileCopyrightText: 2025 Milesime <213074881+milesime@users.noreply.github.com>
#
# SPDX-License-Identifier: GPL-2.0-only

name: Build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - dune
      - dune-project
      - "**.ml"
      - "**.mli"
      - "**.mly"
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yml
      - dune
      - dune-project
      - "**.ml"
      - "**.mli"
      - "**.mly"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            display-name: Ubuntu
            artifact: yod-x86_64-linux
          - os: macos-latest
            display-name: macOS
            artifact: yod-arm64-darwin
          - os: windows-latest
            display-name: Windows
            artifact: yod-x86_64-windows

    runs-on: ${{ matrix.os }}
    name: Build with OCaml 5.3.0 on ${{ matrix.display-name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up OCaml 5.3.0
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.5.3.0+options,ocaml-option-flambda

      - name: Install dependencies
        run: opam install --deps-only .

      - name: Build
        run: opam exec -- dune build --profile release

      - name: Upload the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: _build/default/bin/main.exe
